### ISSUE TITLE
RESOLVED: Setup instructions differ for Windows 10 for Python 3.

### ISSUE THREAD

**Issue by adamfehnel** [goatrocks/-ma-vax-scrape#1]
Hey there, running "pip install -r requirements.txt" I get: "ERROR: Could not find a version that satisfies the requirement soupsieve==2.2 (from -r requirements.txt (line 10)) (from versions: 1.2, 1.2.1, 1.3, 1.3.1, 1.4,
1.5, 1.6, 1.6.1, 1.6.2, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.8, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6)
ERROR: No matching distribution found for soupsieve==2.2 (from -r requirements.txt (line 10))"

and, when running "python scrape.py" I get: "  File "scrape.py", line 118
    url = f"https://www.cvs.com/immunizations/covid-19-vaccine.vaccine-status.MA.json?vaccineinfo"
                                                                                                 ^
SyntaxError: invalid syntax"

I don't see what could be wrong with that string, but I'm not a python guy.

**Comment by adamfehnel** [comment]
I realized I was using an older version of Python when calling the "python" command, but using "py" gave me a newer version that supports F-strings.  Now I get this error:

Traceback (most recent call last):
  File "D:\Software\Bots\-ma-vax-scrape\scrape.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by adamfehnel** [comment]
"py -m pip install -r requirements.txt" worked to install requirements for Python 3.  After that, "py scrape.py" is running successfully on Windows 10.  Sorry for the issue, but this process might help others in similar boats.

**Comment by goatrocks** [comment]
Thank you! I'll think of a way to make it clearer. Unfortunately the python ecosystem can get really confusing. I'd suggest something like virtualenvwrapper https://virtualenvwrapper.readthedocs.io/en/latest/ if you think you might be working on multiple python projects/versions tbh
